/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : ExprCppTree.g
 *     -                            On : 2021-08-14 18:11:30
 *     -                for the parser : ExprCppTreeParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

    #include <assert.h>

/* End of Header action.
 * =============================================================================
 */

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ExprCppTreeParserTokenNames[16+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "ASSIGN",
        (pANTLR3_UINT8) "BLOCK",
        (pANTLR3_UINT8) "DIVIDE",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "MINUS",
        (pANTLR3_UINT8) "NEWLINE",
        (pANTLR3_UINT8) "PLUS",
        (pANTLR3_UINT8) "PRINT",
        (pANTLR3_UINT8) "TIMES",
        (pANTLR3_UINT8) "VAR",
        (pANTLR3_UINT8) "WS",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'{'",
        (pANTLR3_UINT8) "'}'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 ExprCppTreeParser_expr_return
	expr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_multDivExpr_return
	multDivExpr    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_atom_return
	atom    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_stmt_return
	stmt    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_stmts_return
	block_stmts    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_block_return
	block    (pExprCppTreeParser ctx);
static 
 ExprCppTreeParser_prog_return
	prog    (pExprCppTreeParser ctx);
static void	ExprCppTreeParserFree(pExprCppTreeParser ctx);
static void     ExprCppTreeParserReset (pExprCppTreeParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ExprCppTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new ExprCppTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pExprCppTreeParser
ExprCppTreeParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pExprCppTreeParser) ANTLR3_CALLOC(1, sizeof(ExprCppTreeParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ExprCppTreeParser interface
     */
    ctx->expr	= expr;
    ctx->multDivExpr	= multDivExpr;
    ctx->atom	= atom;
    ctx->stmt	= stmt;
    ctx->block_stmts	= block_stmts;
    ctx->block	= block;
    ctx->prog	= prog;
    ctx->free			= ExprCppTreeParserFree;
    ctx->reset			= ExprCppTreeParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */
ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);

ctx->vectors	= antlr3VectorFactoryNew(0);
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ExprCppTreeParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ExprCppTreeParserReset (pExprCppTreeParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ExprCppTreeParserFree(pExprCppTreeParser ctx)
 {
    /* Free any scope memory
     */

ctx->vectors->close(ctx->vectors);
/* We created the adaptor so we must free it
 */
ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return ExprCppTreeParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multDivExpr_in_expr54  */
static	ANTLR3_BITWORD FOLLOW_multDivExpr_in_expr54_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000A02) };
static  ANTLR3_BITSET_LIST FOLLOW_multDivExpr_in_expr54	= { FOLLOW_multDivExpr_in_expr54_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PLUS_in_expr58  */
static	ANTLR3_BITWORD FOLLOW_PLUS_in_expr58_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_PLUS_in_expr58	= { FOLLOW_PLUS_in_expr58_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MINUS_in_expr63  */
static	ANTLR3_BITWORD FOLLOW_MINUS_in_expr63_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_MINUS_in_expr63	= { FOLLOW_MINUS_in_expr63_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multDivExpr_in_expr67  */
static	ANTLR3_BITWORD FOLLOW_multDivExpr_in_expr67_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000A02) };
static  ANTLR3_BITSET_LIST FOLLOW_multDivExpr_in_expr67	= { FOLLOW_multDivExpr_in_expr67_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multDivExpr99  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multDivExpr99_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002042) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multDivExpr99	= { FOLLOW_atom_in_multDivExpr99_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_TIMES_in_multDivExpr103  */
static	ANTLR3_BITWORD FOLLOW_TIMES_in_multDivExpr103_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_TIMES_in_multDivExpr103	= { FOLLOW_TIMES_in_multDivExpr103_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_DIVIDE_in_multDivExpr108  */
static	ANTLR3_BITWORD FOLLOW_DIVIDE_in_multDivExpr108_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_DIVIDE_in_multDivExpr108	= { FOLLOW_DIVIDE_in_multDivExpr108_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multDivExpr112  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multDivExpr112_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002042) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multDivExpr112	= { FOLLOW_atom_in_multDivExpr112_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_atom140  */
static	ANTLR3_BITWORD FOLLOW_INT_in_atom140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_atom140	= { FOLLOW_INT_in_atom140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom148  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom148_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom148	= { FOLLOW_ID_in_atom148_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_16_in_atom156  */
static	ANTLR3_BITWORD FOLLOW_16_in_atom156_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_16_in_atom156	= { FOLLOW_16_in_atom156_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_atom159  */
static	ANTLR3_BITWORD FOLLOW_expr_in_atom159_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000020000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_atom159	= { FOLLOW_expr_in_atom159_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_17_in_atom161  */
static	ANTLR3_BITWORD FOLLOW_17_in_atom161_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_17_in_atom161	= { FOLLOW_17_in_atom161_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt174  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt174_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt174	= { FOLLOW_expr_in_stmt174_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt176  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt176_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt176	= { FOLLOW_NEWLINE_in_stmt176_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt190  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt190_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt190	= { FOLLOW_ID_in_stmt190_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt192  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt192_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt192	= { FOLLOW_ASSIGN_in_stmt192_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt194  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt194_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt194	= { FOLLOW_expr_in_stmt194_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt196  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt196_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt196	= { FOLLOW_NEWLINE_in_stmt196_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt215  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt215_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt215	= { FOLLOW_NEWLINE_in_stmt215_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VAR_in_stmt228  */
static	ANTLR3_BITWORD FOLLOW_VAR_in_stmt228_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000080) };
static  ANTLR3_BITSET_LIST FOLLOW_VAR_in_stmt228	= { FOLLOW_VAR_in_stmt228_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_stmt230  */
static	ANTLR3_BITWORD FOLLOW_ID_in_stmt230_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_stmt230	= { FOLLOW_ID_in_stmt230_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ASSIGN_in_stmt232  */
static	ANTLR3_BITWORD FOLLOW_ASSIGN_in_stmt232_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_ASSIGN_in_stmt232	= { FOLLOW_ASSIGN_in_stmt232_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt234  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt234_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt234	= { FOLLOW_expr_in_stmt234_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt236  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt236_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt236	= { FOLLOW_NEWLINE_in_stmt236_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PRINT_in_stmt254  */
static	ANTLR3_BITWORD FOLLOW_PRINT_in_stmt254_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000010180) };
static  ANTLR3_BITSET_LIST FOLLOW_PRINT_in_stmt254	= { FOLLOW_PRINT_in_stmt254_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_stmt256  */
static	ANTLR3_BITWORD FOLLOW_expr_in_stmt256_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000400) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_stmt256	= { FOLLOW_expr_in_stmt256_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NEWLINE_in_stmt258  */
static	ANTLR3_BITWORD FOLLOW_NEWLINE_in_stmt258_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NEWLINE_in_stmt258	= { FOLLOW_NEWLINE_in_stmt258_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_in_stmt274  */
static	ANTLR3_BITWORD FOLLOW_block_in_stmt274_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_in_stmt274	= { FOLLOW_block_in_stmt274_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_stmt_in_block_stmts315  */
static	ANTLR3_BITWORD FOLLOW_stmt_in_block_stmts315_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000055582) };
static  ANTLR3_BITSET_LIST FOLLOW_stmt_in_block_stmts315	= { FOLLOW_stmt_in_block_stmts315_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_block329  */
static	ANTLR3_BITWORD FOLLOW_18_in_block329_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000D5580) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_block329	= { FOLLOW_18_in_block329_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_stmts_in_block331  */
static	ANTLR3_BITWORD FOLLOW_block_stmts_in_block331_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000080000) };
static  ANTLR3_BITSET_LIST FOLLOW_block_stmts_in_block331	= { FOLLOW_block_stmts_in_block331_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_19_in_block333  */
static	ANTLR3_BITWORD FOLLOW_19_in_block333_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_19_in_block333	= { FOLLOW_19_in_block333_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_block_stmts_in_prog360  */
static	ANTLR3_BITWORD FOLLOW_block_stmts_in_prog360_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_block_stmts_in_prog360	= { FOLLOW_block_stmts_in_prog360_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start expr
 * ExprCppTree.g:16:1: expr : multDivExpr ( ( PLUS ^| MINUS ^) multDivExpr )* ;
 */
static ExprCppTreeParser_expr_return
expr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_expr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    PLUS2;
    pANTLR3_COMMON_TOKEN    MINUS3;
    ExprCppTreeParser_multDivExpr_return multDivExpr1;
    #undef	RETURN_TYPE_multDivExpr1
    #define	RETURN_TYPE_multDivExpr1 ExprCppTreeParser_multDivExpr_return

    ExprCppTreeParser_multDivExpr_return multDivExpr4;
    #undef	RETURN_TYPE_multDivExpr4
    #define	RETURN_TYPE_multDivExpr4 ExprCppTreeParser_multDivExpr_return

    pANTLR3_BASE_TREE PLUS2_tree;
    pANTLR3_BASE_TREE MINUS3_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    PLUS2       = NULL;
    MINUS3       = NULL;
    multDivExpr1.tree = NULL;

    multDivExpr4.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    PLUS2_tree   = NULL;
    MINUS3_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:16:5: ( multDivExpr ( ( PLUS ^| MINUS ^) multDivExpr )* )
        // ExprCppTree.g:16:7: multDivExpr ( ( PLUS ^| MINUS ^) multDivExpr )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_multDivExpr_in_expr54);
            multDivExpr1=multDivExpr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleexprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, multDivExpr1.tree);

            // ExprCppTree.g:16:19: ( ( PLUS ^| MINUS ^) multDivExpr )*

            for (;;)
            {
                int alt2=2;
                switch ( LA(1) )
                {
                case MINUS:
                case PLUS:
                	{
                		alt2=1;
                	}
                    break;

                }

                switch (alt2)
                {
            	case 1:
            	    // ExprCppTree.g:16:20: ( PLUS ^| MINUS ^) multDivExpr
            	    {
            	        // ExprCppTree.g:16:20: ( PLUS ^| MINUS ^)
            	        {
            	            int alt1=2;
            	            switch ( LA(1) )
            	            {
            	            case PLUS:
            	            	{
            	            		alt1=1;
            	            	}
            	                break;
            	            case MINUS:
            	            	{
            	            		alt1=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 1;
            	                EXCEPTION->state        = 0;


            	                goto ruleexprEx;

            	            }

            	            switch (alt1)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:16:21: PLUS ^
            	        	    {
            	        	        PLUS2 = (pANTLR3_COMMON_TOKEN) MATCHT(PLUS, &FOLLOW_PLUS_in_expr58);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        PLUS2_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, PLUS2))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, PLUS2_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:16:29: MINUS ^
            	        	    {
            	        	        MINUS3 = (pANTLR3_COMMON_TOKEN) MATCHT(MINUS, &FOLLOW_MINUS_in_expr63);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleexprEx;
            	        	        }

            	        	        MINUS3_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, MINUS3))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, MINUS3_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_multDivExpr_in_expr67);
            	        multDivExpr4=multDivExpr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleexprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, multDivExpr4.tree);

            	    }
            	    break;

            	default:
            	    goto loop2;	/* break out of the loop */
            	    break;
                }
            }
            loop2: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end expr */

/**
 * $ANTLR start multDivExpr
 * ExprCppTree.g:22:1: multDivExpr : atom ( ( TIMES ^| DIVIDE ^) atom )* ;
 */
static ExprCppTreeParser_multDivExpr_return
multDivExpr(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_multDivExpr_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    TIMES6;
    pANTLR3_COMMON_TOKEN    DIVIDE7;
    ExprCppTreeParser_atom_return atom5;
    #undef	RETURN_TYPE_atom5
    #define	RETURN_TYPE_atom5 ExprCppTreeParser_atom_return

    ExprCppTreeParser_atom_return atom8;
    #undef	RETURN_TYPE_atom8
    #define	RETURN_TYPE_atom8 ExprCppTreeParser_atom_return

    pANTLR3_BASE_TREE TIMES6_tree;
    pANTLR3_BASE_TREE DIVIDE7_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    TIMES6       = NULL;
    DIVIDE7       = NULL;
    atom5.tree = NULL;

    atom8.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    TIMES6_tree   = NULL;
    DIVIDE7_tree   = NULL;


    retval.tree  = NULL;

    {
        // ExprCppTree.g:23:5: ( atom ( ( TIMES ^| DIVIDE ^) atom )* )
        // ExprCppTree.g:23:7: atom ( ( TIMES ^| DIVIDE ^) atom )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            FOLLOWPUSH(FOLLOW_atom_in_multDivExpr99);
            atom5=atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultDivExprEx;
            }

            ADAPTOR->addChild(ADAPTOR, root_0, atom5.tree);

            // ExprCppTree.g:23:12: ( ( TIMES ^| DIVIDE ^) atom )*

            for (;;)
            {
                int alt4=2;
                switch ( LA(1) )
                {
                case DIVIDE:
                case TIMES:
                	{
                		alt4=1;
                	}
                    break;

                }

                switch (alt4)
                {
            	case 1:
            	    // ExprCppTree.g:23:13: ( TIMES ^| DIVIDE ^) atom
            	    {
            	        // ExprCppTree.g:23:13: ( TIMES ^| DIVIDE ^)
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	            case TIMES:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;
            	            case DIVIDE:
            	            	{
            	            		alt3=2;
            	            	}
            	                break;

            	            default:
            	                CONSTRUCTEX();
            	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            	                EXCEPTION->message      = (void *)"";
            	                EXCEPTION->decisionNum  = 3;
            	                EXCEPTION->state        = 0;


            	                goto rulemultDivExprEx;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // ExprCppTree.g:23:14: TIMES ^
            	        	    {
            	        	        TIMES6 = (pANTLR3_COMMON_TOKEN) MATCHT(TIMES, &FOLLOW_TIMES_in_multDivExpr103);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultDivExprEx;
            	        	        }

            	        	        TIMES6_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, TIMES6))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, TIMES6_tree, root_0));


            	        	    }
            	        	    break;
            	        	case 2:
            	        	    // ExprCppTree.g:23:23: DIVIDE ^
            	        	    {
            	        	        DIVIDE7 = (pANTLR3_COMMON_TOKEN) MATCHT(DIVIDE, &FOLLOW_DIVIDE_in_multDivExpr108);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto rulemultDivExprEx;
            	        	        }

            	        	        DIVIDE7_tree = 
            	        	        (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, DIVIDE7))
            	        	        ;
            	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, DIVIDE7_tree, root_0));


            	        	    }
            	        	    break;

            	            }
            	        }

            	        FOLLOWPUSH(FOLLOW_atom_in_multDivExpr112);
            	        atom8=atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultDivExprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, atom8.tree);

            	    }
            	    break;

            	default:
            	    goto loop4;	/* break out of the loop */
            	    break;
                }
            }
            loop4: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultDivExprEx; /* Prevent compiler warnings */
    rulemultDivExprEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end multDivExpr */

/**
 * $ANTLR start atom
 * ExprCppTree.g:30:1: atom : ( INT | ID | '(' ! expr ')' !);
 */
static ExprCppTreeParser_atom_return
atom(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_atom_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT9;
    pANTLR3_COMMON_TOKEN    ID10;
    pANTLR3_COMMON_TOKEN    char_literal11;
    pANTLR3_COMMON_TOKEN    char_literal13;
    ExprCppTreeParser_expr_return expr12;
    #undef	RETURN_TYPE_expr12
    #define	RETURN_TYPE_expr12 ExprCppTreeParser_expr_return

    pANTLR3_BASE_TREE INT9_tree;
    pANTLR3_BASE_TREE ID10_tree;
    pANTLR3_BASE_TREE char_literal11_tree;
    pANTLR3_BASE_TREE char_literal13_tree;

    /* Initialize rule variables
     */

    root_0 = NULL;

    INT9       = NULL;
    ID10       = NULL;
    char_literal11       = NULL;
    char_literal13       = NULL;
    expr12.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    INT9_tree   = NULL;
    ID10_tree   = NULL;
    char_literal11_tree   = NULL;
    char_literal13_tree   = NULL;


    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:30:5: ( INT | ID | '(' ! expr ')' !)

            ANTLR3_UINT32 alt5;

            alt5=3;

            switch ( LA(1) )
            {
            case INT:
            	{
            		alt5=1;
            	}
                break;
            case ID:
            	{
            		alt5=2;
            	}
                break;
            case 16:
            	{
            		alt5=3;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt5)
            {
        	case 1:
        	    // ExprCppTree.g:30:7: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        INT9 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_atom140);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        INT9_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT9));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT9_tree);


        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:31:7: ID
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        ID10 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_atom148);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ID10_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, ID10));
        	        ADAPTOR->addChild(ADAPTOR, root_0, ID10_tree);


        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:32:7: '(' ! expr ')' !
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        char_literal11 = (pANTLR3_COMMON_TOKEN) MATCHT(16, &FOLLOW_16_in_atom156);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_expr_in_atom159);
        	        expr12=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, expr12.tree);

        	        char_literal13 = (pANTLR3_COMMON_TOKEN) MATCHT(17, &FOLLOW_17_in_atom161);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end atom */

/**
 * $ANTLR start stmt
 * ExprCppTree.g:35:1: stmt : ( expr NEWLINE -> expr | ID ASSIGN expr NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->| VAR ID ASSIGN expr NEWLINE -> ^( VAR ID expr ) | PRINT expr NEWLINE -> ^( PRINT expr ) | block );
 */
static ExprCppTreeParser_stmt_return
stmt(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_stmt_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NEWLINE15;
    pANTLR3_COMMON_TOKEN    ID16;
    pANTLR3_COMMON_TOKEN    ASSIGN17;
    pANTLR3_COMMON_TOKEN    NEWLINE19;
    pANTLR3_COMMON_TOKEN    NEWLINE20;
    pANTLR3_COMMON_TOKEN    VAR21;
    pANTLR3_COMMON_TOKEN    ID22;
    pANTLR3_COMMON_TOKEN    ASSIGN23;
    pANTLR3_COMMON_TOKEN    NEWLINE25;
    pANTLR3_COMMON_TOKEN    PRINT26;
    pANTLR3_COMMON_TOKEN    NEWLINE28;
    ExprCppTreeParser_expr_return expr14;
    #undef	RETURN_TYPE_expr14
    #define	RETURN_TYPE_expr14 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr18;
    #undef	RETURN_TYPE_expr18
    #define	RETURN_TYPE_expr18 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr24;
    #undef	RETURN_TYPE_expr24
    #define	RETURN_TYPE_expr24 ExprCppTreeParser_expr_return

    ExprCppTreeParser_expr_return expr27;
    #undef	RETURN_TYPE_expr27
    #define	RETURN_TYPE_expr27 ExprCppTreeParser_expr_return

    ExprCppTreeParser_block_return block29;
    #undef	RETURN_TYPE_block29
    #define	RETURN_TYPE_block29 ExprCppTreeParser_block_return

    pANTLR3_BASE_TREE NEWLINE15_tree;
    pANTLR3_BASE_TREE ID16_tree;
    pANTLR3_BASE_TREE ASSIGN17_tree;
    pANTLR3_BASE_TREE NEWLINE19_tree;
    pANTLR3_BASE_TREE NEWLINE20_tree;
    pANTLR3_BASE_TREE VAR21_tree;
    pANTLR3_BASE_TREE ID22_tree;
    pANTLR3_BASE_TREE ASSIGN23_tree;
    pANTLR3_BASE_TREE NEWLINE25_tree;
    pANTLR3_BASE_TREE PRINT26_tree;
    pANTLR3_BASE_TREE NEWLINE28_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PRINT;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NEWLINE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_VAR;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ID;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_ASSIGN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */

    root_0 = NULL;

    NEWLINE15       = NULL;
    ID16       = NULL;
    ASSIGN17       = NULL;
    NEWLINE19       = NULL;
    NEWLINE20       = NULL;
    VAR21       = NULL;
    ID22       = NULL;
    ASSIGN23       = NULL;
    NEWLINE25       = NULL;
    PRINT26       = NULL;
    NEWLINE28       = NULL;
    expr14.tree = NULL;

    expr18.tree = NULL;

    expr24.tree = NULL;

    expr27.tree = NULL;

    block29.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    NEWLINE15_tree   = NULL;
    ID16_tree   = NULL;
    ASSIGN17_tree   = NULL;
    NEWLINE19_tree   = NULL;
    NEWLINE20_tree   = NULL;
    VAR21_tree   = NULL;
    ID22_tree   = NULL;
    ASSIGN23_tree   = NULL;
    NEWLINE25_tree   = NULL;
    PRINT26_tree   = NULL;
    NEWLINE28_tree   = NULL;

    stream_PRINT   = NULL;
    #define CREATE_stream_PRINT  if (stream_PRINT == NULL) {stream_PRINT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PRINT"); } 
    stream_NEWLINE   = NULL;
    #define CREATE_stream_NEWLINE  if (stream_NEWLINE == NULL) {stream_NEWLINE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NEWLINE"); } 
    stream_VAR   = NULL;
    #define CREATE_stream_VAR  if (stream_VAR == NULL) {stream_VAR = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token VAR"); } 
    stream_ID   = NULL;
    #define CREATE_stream_ID  if (stream_ID == NULL) {stream_ID = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ID"); } 
    stream_ASSIGN   = NULL;
    #define CREATE_stream_ASSIGN  if (stream_ASSIGN == NULL) {stream_ASSIGN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token ASSIGN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;

    {
        {
            //  ExprCppTree.g:35:5: ( expr NEWLINE -> expr | ID ASSIGN expr NEWLINE -> ^( ASSIGN ID expr ) | NEWLINE ->| VAR ID ASSIGN expr NEWLINE -> ^( VAR ID expr ) | PRINT expr NEWLINE -> ^( PRINT expr ) | block )

            ANTLR3_UINT32 alt6;

            alt6=6;

            switch ( LA(1) )
            {
            case INT:
            case 16:
            	{
            		alt6=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case ASSIGN:
            			{
            				alt6=2;
            			}
            		    break;
            		case DIVIDE:
            		case MINUS:
            		case NEWLINE:
            		case PLUS:
            		case TIMES:
            			{
            				alt6=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 6;
            		    EXCEPTION->state        = 2;


            		    goto rulestmtEx;

            		}

            	}
                break;
            case NEWLINE:
            	{
            		alt6=3;
            	}
                break;
            case VAR:
            	{
            		alt6=4;
            	}
                break;
            case PRINT:
            	{
            		alt6=5;
            	}
                break;
            case 18:
            	{
            		alt6=6;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto rulestmtEx;

            }

            switch (alt6)
            {
        	case 1:
        	    // ExprCppTree.g:35:7: expr NEWLINE
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_stmt174);
        	        expr14=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr14.tree, NULL);

        	        NEWLINE15 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt176);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE15, NULL);


        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 35:20: -> expr
        	        	{
        	        	    ADAPTOR->addChild(ADAPTOR, root_0, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // ExprCppTree.g:36:7: ID ASSIGN expr NEWLINE
        	    {
        	        ID16 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt190);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID16, NULL);


        	        ASSIGN17 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt192);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN17, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt194);
        	        expr18=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr18.tree, NULL);

        	        NEWLINE19 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt196);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE19, NULL);


        	        /* AST REWRITE
        	         * elements          : ASSIGN, expr, ID
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 36:30: -> ^( ASSIGN ID expr )
        	        	{
        	        	    // ExprCppTree.g:36:33: ^( ASSIGN ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_ASSIGN == NULL ? NULL : stream_ASSIGN->nextNode(stream_ASSIGN)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // ExprCppTree.g:37:7: NEWLINE
        	    {
        	        NEWLINE20 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt215);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE20, NULL);


        	        /* AST REWRITE
        	         * elements          : 
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 37:15: ->
        	        	{
        	        	    root_0 = NULL; /* <-- rewriteEmptyAlt()) */
        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 4:
        	    // ExprCppTree.g:38:7: VAR ID ASSIGN expr NEWLINE
        	    {
        	        VAR21 = (pANTLR3_COMMON_TOKEN) MATCHT(VAR, &FOLLOW_VAR_in_stmt228);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_VAR; stream_VAR->add(stream_VAR, VAR21, NULL);


        	        ID22 = (pANTLR3_COMMON_TOKEN) MATCHT(ID, &FOLLOW_ID_in_stmt230);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ID; stream_ID->add(stream_ID, ID22, NULL);


        	        ASSIGN23 = (pANTLR3_COMMON_TOKEN) MATCHT(ASSIGN, &FOLLOW_ASSIGN_in_stmt232);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_ASSIGN; stream_ASSIGN->add(stream_ASSIGN, ASSIGN23, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt234);
        	        expr24=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr24.tree, NULL);

        	        NEWLINE25 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt236);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE25, NULL);


        	        /* AST REWRITE
        	         * elements          : VAR, expr, ID
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 38:34: -> ^( VAR ID expr )
        	        	{
        	        	    // ExprCppTree.g:38:37: ^( VAR ID expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_VAR == NULL ? NULL : stream_VAR->nextNode(stream_VAR)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, 
        	        	        stream_ID == NULL ? NULL : stream_ID->nextNode(stream_ID)
        	        	        );

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 5:
        	    // ExprCppTree.g:39:7: PRINT expr NEWLINE
        	    {
        	        PRINT26 = (pANTLR3_COMMON_TOKEN) MATCHT(PRINT, &FOLLOW_PRINT_in_stmt254);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_PRINT; stream_PRINT->add(stream_PRINT, PRINT26, NULL);


        	        FOLLOWPUSH(FOLLOW_expr_in_stmt256);
        	        expr27=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr27.tree, NULL);

        	        NEWLINE28 = (pANTLR3_COMMON_TOKEN) MATCHT(NEWLINE, &FOLLOW_NEWLINE_in_stmt258);
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }
        	         
        	        CREATE_stream_NEWLINE; stream_NEWLINE->add(stream_NEWLINE, NEWLINE28, NULL);


        	        /* AST REWRITE
        	         * elements          : PRINT, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 39:26: -> ^( PRINT expr )
        	        	{
        	        	    // ExprCppTree.g:39:29: ^( PRINT expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
        	        	        stream_PRINT == NULL ? NULL : stream_PRINT->nextNode(stream_PRINT)
        	        	        , root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}


        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 6:
        	    // ExprCppTree.g:40:7: block
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        FOLLOWPUSH(FOLLOW_block_in_stmt274);
        	        block29=block(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestmtEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, block29.tree);

        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto rulestmtEx; /* Prevent compiler warnings */
    rulestmtEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_PRINT != NULL) stream_PRINT->free(stream_PRINT);
        if (stream_NEWLINE != NULL) stream_NEWLINE->free(stream_NEWLINE);
        if (stream_VAR != NULL) stream_VAR->free(stream_VAR);
        if (stream_ID != NULL) stream_ID->free(stream_ID);
        if (stream_ASSIGN != NULL) stream_ASSIGN->free(stream_ASSIGN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end stmt */

/**
 * $ANTLR start block_stmts
 * ExprCppTree.g:48:1: block_stmts : ( stmt )* ;
 */
static ExprCppTreeParser_block_stmts_return
block_stmts(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_stmts_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_stmt_return stmt30;
    #undef	RETURN_TYPE_stmt30
    #define	RETURN_TYPE_stmt30 ExprCppTreeParser_stmt_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    stmt30.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:48:12: ( ( stmt )* )
        // ExprCppTree.g:48:14: ( stmt )*
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:48:14: ( stmt )*

            for (;;)
            {
                int alt7=2;
                switch ( LA(1) )
                {
                case ID:
                case INT:
                case NEWLINE:
                case PRINT:
                case VAR:
                case 16:
                case 18:
                	{
                		alt7=1;
                	}
                    break;

                }

                switch (alt7)
                {
            	case 1:
            	    // ExprCppTree.g:48:14: stmt
            	    {
            	        FOLLOWPUSH(FOLLOW_stmt_in_block_stmts315);
            	        stmt30=stmt(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleblock_stmtsEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, stmt30.tree);

            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblock_stmtsEx; /* Prevent compiler warnings */
    ruleblock_stmtsEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block_stmts */

/**
 * $ANTLR start block
 * ExprCppTree.g:51:1: block : '{' block_stmts '}' -> ^( BLOCK block_stmts ) ;
 */
static ExprCppTreeParser_block_return
block(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_block_return retval;


    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal31;
    pANTLR3_COMMON_TOKEN    char_literal33;
    ExprCppTreeParser_block_stmts_return block_stmts32;
    #undef	RETURN_TYPE_block_stmts32
    #define	RETURN_TYPE_block_stmts32 ExprCppTreeParser_block_stmts_return

    pANTLR3_BASE_TREE char_literal31_tree;
    pANTLR3_BASE_TREE char_literal33_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_18;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_19;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_block_stmts;
    /* Initialize rule variables
     */

    root_0 = NULL;

    char_literal31       = NULL;
    char_literal33       = NULL;
    block_stmts32.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;


    char_literal31_tree   = NULL;
    char_literal33_tree   = NULL;

    stream_18   = NULL;
    #define CREATE_stream_18  if (stream_18 == NULL) {stream_18 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 18"); } 
    stream_19   = NULL;
    #define CREATE_stream_19  if (stream_19 == NULL) {stream_19 = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token 19"); } 
    stream_block_stmts   = NULL;
    #define CREATE_stream_block_stmts  if (stream_block_stmts == NULL) {stream_block_stmts = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule block_stmts"); }

    retval.tree  = NULL;

    {
        // ExprCppTree.g:51:6: ( '{' block_stmts '}' -> ^( BLOCK block_stmts ) )
        // ExprCppTree.g:51:8: '{' block_stmts '}'
        {
            char_literal31 = (pANTLR3_COMMON_TOKEN) MATCHT(18, &FOLLOW_18_in_block329);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_18; stream_18->add(stream_18, char_literal31, NULL);


            FOLLOWPUSH(FOLLOW_block_stmts_in_block331);
            block_stmts32=block_stmts(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }

            CREATE_stream_block_stmts; stream_block_stmts->add(stream_block_stmts, block_stmts32.tree, NULL);

            char_literal33 = (pANTLR3_COMMON_TOKEN) MATCHT(19, &FOLLOW_19_in_block333);
            if  (HASEXCEPTION())
            {
                goto ruleblockEx;
            }
             
            CREATE_stream_19; stream_19->add(stream_19, char_literal33, NULL);


            /* AST REWRITE
             * elements          : block_stmts
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 51:28: -> ^( BLOCK block_stmts )
            	{
            	    // ExprCppTree.g:51:31: ^( BLOCK block_stmts )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, 
            	        (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, BLOCK, (pANTLR3_UINT8)"BLOCK")
            	        , root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_block_stmts == NULL ? NULL : stream_block_stmts->nextTree(stream_block_stmts));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}


            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }

    // This is where rules clean up and exit
    //
    goto ruleblockEx; /* Prevent compiler warnings */
    ruleblockEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_18 != NULL) stream_18->free(stream_18);
        if (stream_19 != NULL) stream_19->free(stream_19);
        if (stream_block_stmts != NULL) stream_block_stmts->free(stream_block_stmts);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end block */

/**
 * $ANTLR start prog
 * ExprCppTree.g:55:1: prog : ( block_stmts ) ;
 */
static ExprCppTreeParser_prog_return
prog(pExprCppTreeParser ctx)
{
    ExprCppTreeParser_prog_return retval;


    pANTLR3_BASE_TREE root_0;

    ExprCppTreeParser_block_stmts_return block_stmts34;
    #undef	RETURN_TYPE_block_stmts34
    #define	RETURN_TYPE_block_stmts34 ExprCppTreeParser_block_stmts_return


    /* Initialize rule variables
     */

    root_0 = NULL;

    block_stmts34.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;




    retval.tree  = NULL;

    {
        // ExprCppTree.g:56:5: ( ( block_stmts ) )
        // ExprCppTree.g:56:7: ( block_stmts )
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // ExprCppTree.g:56:7: ( block_stmts )
            // ExprCppTree.g:56:8: block_stmts
            {
                FOLLOWPUSH(FOLLOW_block_stmts_in_prog360);
                block_stmts34=block_stmts(ctx);

                FOLLOWPOP();
                if  (HASEXCEPTION())
                {
                    goto ruleprogEx;
                }

                ADAPTOR->addChild(ADAPTOR, root_0, block_stmts34.tree);

                {
                    pANTLR3_STRING s = (block_stmts34.tree)->toStringTree((block_stmts34.tree));
                                 assert(s->chars);
                                 printf(" tree %s\n", s->chars);
                                
                }


            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);


    	retval.stop = LT(-1);

    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }
    return retval;
}
/* $ANTLR end prog */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
